baseURL = "/"
languageCode = "en-us"
title = "jmmr | software dev log"
theme = "hugo-classic"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "vs"
        tabWidth = 2

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 3
[[menu.main]]
    name = "Uses"
    url = "/uses/"
    weight = 4
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Notes on Software Development, Home Lab Networking, and Dev Ops"
    footer = "[GitHub](https://github.com/jimueller)"
