baseURL = "/"
languageCode = "en-us"
title = "jmmr"
theme = "hugo-classic"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "vs"
        tabWidth = 2

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "Uses"
    url = "/uses/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Software learnings with a ridiculous theme."
    footer = "[Github](https://github.com/jimueller)"
