# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cibuilds/hugo:0.80

    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: $CIRCLE_WORKING_DIRECTORY/public

    steps:
      # checkout the repo
      - checkout

      - run: hugo version
      - run: HUGO_ENV=production hugo -v --minify

      - add_ssh_keys:
          fingerprints:
            - "e4:95:c8:16:62:46:0c:d2:ff:bd:01:ac:c3:20:d3:6b"

      - run: echo ${KNOWN_HOST} >> ~/.ssh/known_hosts

      - deploy:
          name: "Deploy via Rsync"
          command: rsync -va --delete ~/hugo/public/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
          
      - run:
          name: Delete deflate cache
          command: |
            ssh ${DEPLOY_USER}@${DEPLOY_HOST} ${CLEAR_CACHE_CMD}
